## Part 0.0

loom: https://www.loom.com/share/88b6a4c9d86c4b26b0868cb42a212f2f

## Part 0.1

loom: https://www.loom.com/share/5673e3b4e3e34162ad5eb77676e48a87

## Part 1

loom: https://www.loom.com/share/2186678ab46b45aa821c6ecb5b102505

`source ~/.venv/try-pyeventsourcing-310/bin/activate` (Please use your own naming of the venv. This happens to be mine.)

`cd part1-try-pyeventsourcing`

`pytest -c pytest.ini`

First, fail the test because the domainmodel and application are not there.

Then, add the domainmodel and application and pass the test.

## Part 2

loom: https://www.loom.com/share/5d7e2e0fb33746b5829956f3221f4fd9

`source ~/.venv/try-pyeventsourcing-310/bin/activate` (Please use your own naming of the venv. This happens to be mine.)

`cd part2-try-pyeventsourcing`

go to `part2-try-pyeventsourcing/domainmodel.py`

follow the pattern of the Dog to write Todos

then `pytest -c pytest.ini` or `pytest -c pytest.ini -k "test_exercise"`

## Part 3

loom: https://www.loom.com/share/828944cc90874a9ea04d1cc1585c5258 (warnig! subject to reshoot)

`source ~/.venv/try-pyeventsourcing-310/bin/activate` (Please use your own naming of the venv. This happens to be mine.)

`cd part3-try-pyeventsourcing`

go to `part3-try-pyeventsourcing/domainmodel.py`

follow the pattern of the Dog to write Todos

then `pytest -c pytest.ini -k "test_application_for_part3"`